name: Build and publish on Ubuntu

on: [push]


# security: restrict permissions for CI jobs.
#permissions:
 # contents: read

jobs:
  build-vpoplib:
    name: Build and publish pybeepop+ package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout BeePop+ code
        uses: actions/checkout@v4
        with:
          repository: quanted/vpoplib
          path: vpoplib
      - name: Build BeePop+
        working-directory: /home/runner/work/pybeepop/pybeepop/vpoplib
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON ..  	
          cmake --build . --config Release
          mv ./liblibvpop.so ./beepop_ubuntu.so
      - name: Upload compiled library artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-ubuntu
          path: /home/runner/work/pybeepop/pybeepop/vpoplib/build/*.so

  build-wheels:
    name: Build pybeepop wheels
    needs: build-vpoplib
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pybeepop code
        uses: actions/checkout@v4
        with:
          ref: build-wheel

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Download pre-compiled BeePop+
        uses: actions/download-artifact@v4
        with:
          name: compiled-ubuntu
          path: /home/runner/work/pybeepop/pybeepop/lib

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -y

      - name: Update PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Update Poetry configuration
        run: poetry config virtualenvs.create false
      
      - name: Install dependencies
        working-directory: /home/runner/work/pybeepop/pybeepop
        run: poetry install --sync --no-interaction

      - name: Package project
        working-directory: /home/runner/work/pybeepop/pybeepop
        run: poetry build

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-ubuntu
          path: /home/runner/work/pybeepop/pybeepop/dist/*.whl

#      - name: Publish package distributions to PyPI
#        uses: pypa/gh-action-pypi-publish@release/v1