name: CIBuildWheel

on:
    push:
#      branches:
#        - main
        paths:
        - pybeepop/**
        - .github/workflows/ci-build-wheel.yml
        - pyproject.toml
      #    tags:        
  #      - '*.*.*'
    pull_request:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Checkout BeePop+ code
        uses: actions/checkout@v4
        with:
            repository: quanted/vpoplib
            ref: dev
            path: beepop

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.0
        env:
          CIBW_ARCHS: auto64
          CIBW_BUILD: cp39-*
        #    ...
        with:
        #   package-dir: .
        #   output-dir: wheelhouse
          config-file: "pyproject_cibw.toml"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl